"""initial

Revision ID: 31ae83e40c68
Revises: 
Create Date: 2026-07-20 13:30:09.404533+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers — used by Alembic
revision: str = '31ae83e40c68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='Tenant this row belongs to. All queries MUST filter by this.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('target_company_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.String(), nullable=True),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_leads_email'), 'generated_leads', ['email'], unique=False)
    op.create_index(op.f('ix_generated_leads_status'), 'generated_leads', ['status'], unique=False)
    op.create_index(op.f('ix_generated_leads_target_company_id'), 'generated_leads', ['target_company_id'], unique=False)
    op.create_index(op.f('ix_generated_leads_tenant_id'), 'generated_leads', ['tenant_id'], unique=False)
    op.create_table('job_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='Tenant this row belongs to. All queries MUST filter by this.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('task_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_statuses_status'), 'job_statuses', ['status'], unique=False)
    op.create_index(op.f('ix_job_statuses_task_name'), 'job_statuses', ['task_name'], unique=False)
    op.create_index(op.f('ix_job_statuses_tenant_id'), 'job_statuses', ['tenant_id'], unique=False)
    op.create_table('target_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='Tenant this row belongs to. All queries MUST filter by this.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('employee_count_min', sa.Integer(), nullable=True),
    sa.Column('employee_count_max', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_usd', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('enrichment_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_companies_domain'), 'target_companies', ['domain'], unique=False)
    op.create_index(op.f('ix_target_companies_enrichment_status'), 'target_companies', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_target_companies_name'), 'target_companies', ['name'], unique=False)
    op.create_index(op.f('ix_target_companies_tenant_id'), 'target_companies', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='Tenant this row belongs to. All queries MUST filter by this.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='member', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_user_profiles_tenant_id'), 'user_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_tenant_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_target_companies_tenant_id'), table_name='target_companies')
    op.drop_index(op.f('ix_target_companies_name'), table_name='target_companies')
    op.drop_index(op.f('ix_target_companies_enrichment_status'), table_name='target_companies')
    op.drop_index(op.f('ix_target_companies_domain'), table_name='target_companies')
    op.drop_table('target_companies')
    op.drop_index(op.f('ix_job_statuses_tenant_id'), table_name='job_statuses')
    op.drop_index(op.f('ix_job_statuses_task_name'), table_name='job_statuses')
    op.drop_index(op.f('ix_job_statuses_status'), table_name='job_statuses')
    op.drop_table('job_statuses')
    op.drop_index(op.f('ix_generated_leads_tenant_id'), table_name='generated_leads')
    op.drop_index(op.f('ix_generated_leads_target_company_id'), table_name='generated_leads')
    op.drop_index(op.f('ix_generated_leads_status'), table_name='generated_leads')
    op.drop_index(op.f('ix_generated_leads_email'), table_name='generated_leads')
    op.drop_table('generated_leads')
    # ### end Alembic commands ###
